/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlatformPoliciesRouteImport } from './routes/platform-policies'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GuestWorkspaceRouteImport } from './routes/guest-workspace'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FieldRouteImport } from './routes/field'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ErpRouteImport } from './routes/erp'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AddonsRouteImport } from './routes/addons'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FieldIndexRouteImport } from './routes/field.index'
import { Route as ErpIndexRouteImport } from './routes/erp.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as FieldTodayRouteRouteImport } from './routes/field.today-route'
import { Route as FieldSettingsRouteImport } from './routes/field.settings'
import { Route as FieldProfileRouteImport } from './routes/field.profile'
import { Route as FieldPerformanceRouteImport } from './routes/field.performance'
import { Route as FieldOfflineRouteImport } from './routes/field.offline'
import { Route as FieldNotificationsRouteImport } from './routes/field.notifications'
import { Route as FieldHelpRouteImport } from './routes/field.help'
import { Route as FieldHandoverRouteImport } from './routes/field.handover'
import { Route as FieldExpensesRouteImport } from './routes/field.expenses'
import { Route as FieldAttendanceRouteImport } from './routes/field.attendance'
import { Route as ErpSubscriptionRouteImport } from './routes/erp.subscription'
import { Route as ErpSettingsRouteImport } from './routes/erp.settings'
import { Route as ErpSalaryRouteImport } from './routes/erp.salary'
import { Route as ErpReportsRouteImport } from './routes/erp.reports'
import { Route as ErpReconciliationRouteImport } from './routes/erp.reconciliation'
import { Route as ErpProfileRouteImport } from './routes/erp.profile'
import { Route as ErpNotificationsRouteImport } from './routes/erp.notifications'
import { Route as ErpExpensesRouteImport } from './routes/erp.expenses'
import { Route as ErpBusinessRouteImport } from './routes/erp.business'
import { Route as ErpAnalyticsRouteImport } from './routes/erp.analytics'
import { Route as DevRouteSmokeRouteImport } from './routes/dev.route-smoke'
import { Route as AppUpgradeRouteImport } from './routes/app.upgrade'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppExpensesRouteImport } from './routes/app.expenses'
import { Route as AppCustomersRouteImport } from './routes/app.customers'
import { Route as AppCalculatorRouteImport } from './routes/app.calculator'
import { Route as AdminUpgradeRequestsRouteImport } from './routes/admin.upgrade-requests'
import { Route as AdminSystemHealthRouteImport } from './routes/admin.system-health'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMasterDataRouteImport } from './routes/admin.master-data'
import { Route as AdminLendersRouteImport } from './routes/admin.lenders'
import { Route as AdminInvoicesRouteImport } from './routes/admin.invoices'
import { Route as AdminGuestPlanRouteImport } from './routes/admin.guest-plan'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminConfigurationRouteImport } from './routes/admin.configuration'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as FieldCustomersIndexRouteImport } from './routes/field.customers.index'
import { Route as FieldCollectionsIndexRouteImport } from './routes/field.collections.index'
import { Route as ErpRoutesIndexRouteImport } from './routes/erp.routes.index'
import { Route as ErpLoansIndexRouteImport } from './routes/erp.loans.index'
import { Route as ErpEmployeesIndexRouteImport } from './routes/erp.employees.index'
import { Route as ErpCustomersIndexRouteImport } from './routes/erp.customers.index'
import { Route as ErpCollectionsIndexRouteImport } from './routes/erp.collections.index'
import { Route as ErpAreasIndexRouteImport } from './routes/erp.areas.index'
import { Route as AppCollectionsIndexRouteImport } from './routes/app.collections.index'
import { Route as FieldCustomersIdRouteImport } from './routes/field.customers.$id'
import { Route as FieldCollectionsNewRouteImport } from './routes/field.collections.new'
import { Route as ErpRoutesIdRouteImport } from './routes/erp.routes.$id'
import { Route as ErpLoansIdRouteImport } from './routes/erp.loans.$id'
import { Route as ErpEmployeesIdRouteImport } from './routes/erp.employees.$id'
import { Route as ErpCustomersIdRouteImport } from './routes/erp.customers.$id'
import { Route as ErpCollectionsTodayRouteImport } from './routes/erp.collections.today'
import { Route as ErpAreasIdRouteImport } from './routes/erp.areas.$id'
import { Route as AppCollectionsNewRouteImport } from './routes/app.collections.new'
import { Route as AppCollectionsBatchRouteImport } from './routes/app.collections.batch'
import { Route as AdminLendersIdRouteImport } from './routes/admin.lenders.$id'
import { Route as AppCollectionsIdIndexRouteImport } from './routes/app.collections.$id.index'
import { Route as AppCollectionsIdEditRouteImport } from './routes/app.collections.$id.edit'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformPoliciesRoute = PlatformPoliciesRouteImport.update({
  id: '/platform-policies',
  path: '/platform-policies',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestWorkspaceRoute = GuestWorkspaceRouteImport.update({
  id: '/guest-workspace',
  path: '/guest-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldRoute = FieldRouteImport.update({
  id: '/field',
  path: '/field',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ErpRoute = ErpRouteImport.update({
  id: '/erp',
  path: '/erp',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AddonsRoute = AddonsRouteImport.update({
  id: '/addons',
  path: '/addons',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldIndexRoute = FieldIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FieldRoute,
} as any)
const ErpIndexRoute = ErpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ErpRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const FieldTodayRouteRoute = FieldTodayRouteRouteImport.update({
  id: '/today-route',
  path: '/today-route',
  getParentRoute: () => FieldRoute,
} as any)
const FieldSettingsRoute = FieldSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => FieldRoute,
} as any)
const FieldProfileRoute = FieldProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => FieldRoute,
} as any)
const FieldPerformanceRoute = FieldPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => FieldRoute,
} as any)
const FieldOfflineRoute = FieldOfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => FieldRoute,
} as any)
const FieldNotificationsRoute = FieldNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => FieldRoute,
} as any)
const FieldHelpRoute = FieldHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => FieldRoute,
} as any)
const FieldHandoverRoute = FieldHandoverRouteImport.update({
  id: '/handover',
  path: '/handover',
  getParentRoute: () => FieldRoute,
} as any)
const FieldExpensesRoute = FieldExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => FieldRoute,
} as any)
const FieldAttendanceRoute = FieldAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => FieldRoute,
} as any)
const ErpSubscriptionRoute = ErpSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => ErpRoute,
} as any)
const ErpSettingsRoute = ErpSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ErpRoute,
} as any)
const ErpSalaryRoute = ErpSalaryRouteImport.update({
  id: '/salary',
  path: '/salary',
  getParentRoute: () => ErpRoute,
} as any)
const ErpReportsRoute = ErpReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ErpRoute,
} as any)
const ErpReconciliationRoute = ErpReconciliationRouteImport.update({
  id: '/reconciliation',
  path: '/reconciliation',
  getParentRoute: () => ErpRoute,
} as any)
const ErpProfileRoute = ErpProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ErpRoute,
} as any)
const ErpNotificationsRoute = ErpNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ErpRoute,
} as any)
const ErpExpensesRoute = ErpExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => ErpRoute,
} as any)
const ErpBusinessRoute = ErpBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => ErpRoute,
} as any)
const ErpAnalyticsRoute = ErpAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ErpRoute,
} as any)
const DevRouteSmokeRoute = DevRouteSmokeRouteImport.update({
  id: '/dev/route-smoke',
  path: '/dev/route-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUpgradeRoute = AppUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCalculatorRoute = AppCalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => AppRoute,
} as any)
const AdminUpgradeRequestsRoute = AdminUpgradeRequestsRouteImport.update({
  id: '/upgrade-requests',
  path: '/upgrade-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemHealthRoute = AdminSystemHealthRouteImport.update({
  id: '/system-health',
  path: '/system-health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMasterDataRoute = AdminMasterDataRouteImport.update({
  id: '/master-data',
  path: '/master-data',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLendersRoute = AdminLendersRouteImport.update({
  id: '/lenders',
  path: '/lenders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGuestPlanRoute = AdminGuestPlanRouteImport.update({
  id: '/guest-plan',
  path: '/guest-plan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigurationRoute = AdminConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const FieldCustomersIndexRoute = FieldCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => FieldRoute,
} as any)
const FieldCollectionsIndexRoute = FieldCollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => FieldRoute,
} as any)
const ErpRoutesIndexRoute = ErpRoutesIndexRouteImport.update({
  id: '/routes/',
  path: '/routes/',
  getParentRoute: () => ErpRoute,
} as any)
const ErpLoansIndexRoute = ErpLoansIndexRouteImport.update({
  id: '/loans/',
  path: '/loans/',
  getParentRoute: () => ErpRoute,
} as any)
const ErpEmployeesIndexRoute = ErpEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => ErpRoute,
} as any)
const ErpCustomersIndexRoute = ErpCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => ErpRoute,
} as any)
const ErpCollectionsIndexRoute = ErpCollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => ErpRoute,
} as any)
const ErpAreasIndexRoute = ErpAreasIndexRouteImport.update({
  id: '/areas/',
  path: '/areas/',
  getParentRoute: () => ErpRoute,
} as any)
const AppCollectionsIndexRoute = AppCollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => AppRoute,
} as any)
const FieldCustomersIdRoute = FieldCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => FieldRoute,
} as any)
const FieldCollectionsNewRoute = FieldCollectionsNewRouteImport.update({
  id: '/collections/new',
  path: '/collections/new',
  getParentRoute: () => FieldRoute,
} as any)
const ErpRoutesIdRoute = ErpRoutesIdRouteImport.update({
  id: '/routes/$id',
  path: '/routes/$id',
  getParentRoute: () => ErpRoute,
} as any)
const ErpLoansIdRoute = ErpLoansIdRouteImport.update({
  id: '/loans/$id',
  path: '/loans/$id',
  getParentRoute: () => ErpRoute,
} as any)
const ErpEmployeesIdRoute = ErpEmployeesIdRouteImport.update({
  id: '/employees/$id',
  path: '/employees/$id',
  getParentRoute: () => ErpRoute,
} as any)
const ErpCustomersIdRoute = ErpCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => ErpRoute,
} as any)
const ErpCollectionsTodayRoute = ErpCollectionsTodayRouteImport.update({
  id: '/collections/today',
  path: '/collections/today',
  getParentRoute: () => ErpRoute,
} as any)
const ErpAreasIdRoute = ErpAreasIdRouteImport.update({
  id: '/areas/$id',
  path: '/areas/$id',
  getParentRoute: () => ErpRoute,
} as any)
const AppCollectionsNewRoute = AppCollectionsNewRouteImport.update({
  id: '/collections/new',
  path: '/collections/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionsBatchRoute = AppCollectionsBatchRouteImport.update({
  id: '/collections/batch',
  path: '/collections/batch',
  getParentRoute: () => AppRoute,
} as any)
const AdminLendersIdRoute = AdminLendersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminLendersRoute,
} as any)
const AppCollectionsIdIndexRoute = AppCollectionsIdIndexRouteImport.update({
  id: '/collections/$id/',
  path: '/collections/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionsIdEditRoute = AppCollectionsIdEditRouteImport.update({
  id: '/collections/$id/edit',
  path: '/collections/$id/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addons': typeof AddonsRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/erp': typeof ErpRouteWithChildren
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/field': typeof FieldRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/guest-workspace': typeof GuestWorkspaceRoute
  '/login': typeof LoginRoute
  '/platform-policies': typeof PlatformPoliciesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/configuration': typeof AdminConfigurationRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/guest-plan': typeof AdminGuestPlanRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/lenders': typeof AdminLendersRouteWithChildren
  '/admin/master-data': typeof AdminMasterDataRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/system-health': typeof AdminSystemHealthRoute
  '/admin/upgrade-requests': typeof AdminUpgradeRequestsRoute
  '/app/calculator': typeof AppCalculatorRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/upgrade': typeof AppUpgradeRoute
  '/dev/route-smoke': typeof DevRouteSmokeRoute
  '/erp/analytics': typeof ErpAnalyticsRoute
  '/erp/business': typeof ErpBusinessRoute
  '/erp/expenses': typeof ErpExpensesRoute
  '/erp/notifications': typeof ErpNotificationsRoute
  '/erp/profile': typeof ErpProfileRoute
  '/erp/reconciliation': typeof ErpReconciliationRoute
  '/erp/reports': typeof ErpReportsRoute
  '/erp/salary': typeof ErpSalaryRoute
  '/erp/settings': typeof ErpSettingsRoute
  '/erp/subscription': typeof ErpSubscriptionRoute
  '/field/attendance': typeof FieldAttendanceRoute
  '/field/expenses': typeof FieldExpensesRoute
  '/field/handover': typeof FieldHandoverRoute
  '/field/help': typeof FieldHelpRoute
  '/field/notifications': typeof FieldNotificationsRoute
  '/field/offline': typeof FieldOfflineRoute
  '/field/performance': typeof FieldPerformanceRoute
  '/field/profile': typeof FieldProfileRoute
  '/field/settings': typeof FieldSettingsRoute
  '/field/today-route': typeof FieldTodayRouteRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/erp/': typeof ErpIndexRoute
  '/field/': typeof FieldIndexRoute
  '/admin/lenders/$id': typeof AdminLendersIdRoute
  '/app/collections/batch': typeof AppCollectionsBatchRoute
  '/app/collections/new': typeof AppCollectionsNewRoute
  '/erp/areas/$id': typeof ErpAreasIdRoute
  '/erp/collections/today': typeof ErpCollectionsTodayRoute
  '/erp/customers/$id': typeof ErpCustomersIdRoute
  '/erp/employees/$id': typeof ErpEmployeesIdRoute
  '/erp/loans/$id': typeof ErpLoansIdRoute
  '/erp/routes/$id': typeof ErpRoutesIdRoute
  '/field/collections/new': typeof FieldCollectionsNewRoute
  '/field/customers/$id': typeof FieldCustomersIdRoute
  '/app/collections/': typeof AppCollectionsIndexRoute
  '/erp/areas/': typeof ErpAreasIndexRoute
  '/erp/collections/': typeof ErpCollectionsIndexRoute
  '/erp/customers/': typeof ErpCustomersIndexRoute
  '/erp/employees/': typeof ErpEmployeesIndexRoute
  '/erp/loans/': typeof ErpLoansIndexRoute
  '/erp/routes/': typeof ErpRoutesIndexRoute
  '/field/collections/': typeof FieldCollectionsIndexRoute
  '/field/customers/': typeof FieldCustomersIndexRoute
  '/app/collections/$id/edit': typeof AppCollectionsIdEditRoute
  '/app/collections/$id/': typeof AppCollectionsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addons': typeof AddonsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guest-workspace': typeof GuestWorkspaceRoute
  '/login': typeof LoginRoute
  '/platform-policies': typeof PlatformPoliciesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/configuration': typeof AdminConfigurationRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/guest-plan': typeof AdminGuestPlanRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/lenders': typeof AdminLendersRouteWithChildren
  '/admin/master-data': typeof AdminMasterDataRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/system-health': typeof AdminSystemHealthRoute
  '/admin/upgrade-requests': typeof AdminUpgradeRequestsRoute
  '/app/calculator': typeof AppCalculatorRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/upgrade': typeof AppUpgradeRoute
  '/dev/route-smoke': typeof DevRouteSmokeRoute
  '/erp/analytics': typeof ErpAnalyticsRoute
  '/erp/business': typeof ErpBusinessRoute
  '/erp/expenses': typeof ErpExpensesRoute
  '/erp/notifications': typeof ErpNotificationsRoute
  '/erp/profile': typeof ErpProfileRoute
  '/erp/reconciliation': typeof ErpReconciliationRoute
  '/erp/reports': typeof ErpReportsRoute
  '/erp/salary': typeof ErpSalaryRoute
  '/erp/settings': typeof ErpSettingsRoute
  '/erp/subscription': typeof ErpSubscriptionRoute
  '/field/attendance': typeof FieldAttendanceRoute
  '/field/expenses': typeof FieldExpensesRoute
  '/field/handover': typeof FieldHandoverRoute
  '/field/help': typeof FieldHelpRoute
  '/field/notifications': typeof FieldNotificationsRoute
  '/field/offline': typeof FieldOfflineRoute
  '/field/performance': typeof FieldPerformanceRoute
  '/field/profile': typeof FieldProfileRoute
  '/field/settings': typeof FieldSettingsRoute
  '/field/today-route': typeof FieldTodayRouteRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/erp': typeof ErpIndexRoute
  '/field': typeof FieldIndexRoute
  '/admin/lenders/$id': typeof AdminLendersIdRoute
  '/app/collections/batch': typeof AppCollectionsBatchRoute
  '/app/collections/new': typeof AppCollectionsNewRoute
  '/erp/areas/$id': typeof ErpAreasIdRoute
  '/erp/collections/today': typeof ErpCollectionsTodayRoute
  '/erp/customers/$id': typeof ErpCustomersIdRoute
  '/erp/employees/$id': typeof ErpEmployeesIdRoute
  '/erp/loans/$id': typeof ErpLoansIdRoute
  '/erp/routes/$id': typeof ErpRoutesIdRoute
  '/field/collections/new': typeof FieldCollectionsNewRoute
  '/field/customers/$id': typeof FieldCustomersIdRoute
  '/app/collections': typeof AppCollectionsIndexRoute
  '/erp/areas': typeof ErpAreasIndexRoute
  '/erp/collections': typeof ErpCollectionsIndexRoute
  '/erp/customers': typeof ErpCustomersIndexRoute
  '/erp/employees': typeof ErpEmployeesIndexRoute
  '/erp/loans': typeof ErpLoansIndexRoute
  '/erp/routes': typeof ErpRoutesIndexRoute
  '/field/collections': typeof FieldCollectionsIndexRoute
  '/field/customers': typeof FieldCustomersIndexRoute
  '/app/collections/$id/edit': typeof AppCollectionsIdEditRoute
  '/app/collections/$id': typeof AppCollectionsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/addons': typeof AddonsRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/erp': typeof ErpRouteWithChildren
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/field': typeof FieldRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/guest-workspace': typeof GuestWorkspaceRoute
  '/login': typeof LoginRoute
  '/platform-policies': typeof PlatformPoliciesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/configuration': typeof AdminConfigurationRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/guest-plan': typeof AdminGuestPlanRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/lenders': typeof AdminLendersRouteWithChildren
  '/admin/master-data': typeof AdminMasterDataRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/system-health': typeof AdminSystemHealthRoute
  '/admin/upgrade-requests': typeof AdminUpgradeRequestsRoute
  '/app/calculator': typeof AppCalculatorRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/upgrade': typeof AppUpgradeRoute
  '/dev/route-smoke': typeof DevRouteSmokeRoute
  '/erp/analytics': typeof ErpAnalyticsRoute
  '/erp/business': typeof ErpBusinessRoute
  '/erp/expenses': typeof ErpExpensesRoute
  '/erp/notifications': typeof ErpNotificationsRoute
  '/erp/profile': typeof ErpProfileRoute
  '/erp/reconciliation': typeof ErpReconciliationRoute
  '/erp/reports': typeof ErpReportsRoute
  '/erp/salary': typeof ErpSalaryRoute
  '/erp/settings': typeof ErpSettingsRoute
  '/erp/subscription': typeof ErpSubscriptionRoute
  '/field/attendance': typeof FieldAttendanceRoute
  '/field/expenses': typeof FieldExpensesRoute
  '/field/handover': typeof FieldHandoverRoute
  '/field/help': typeof FieldHelpRoute
  '/field/notifications': typeof FieldNotificationsRoute
  '/field/offline': typeof FieldOfflineRoute
  '/field/performance': typeof FieldPerformanceRoute
  '/field/profile': typeof FieldProfileRoute
  '/field/settings': typeof FieldSettingsRoute
  '/field/today-route': typeof FieldTodayRouteRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/erp/': typeof ErpIndexRoute
  '/field/': typeof FieldIndexRoute
  '/admin/lenders/$id': typeof AdminLendersIdRoute
  '/app/collections/batch': typeof AppCollectionsBatchRoute
  '/app/collections/new': typeof AppCollectionsNewRoute
  '/erp/areas/$id': typeof ErpAreasIdRoute
  '/erp/collections/today': typeof ErpCollectionsTodayRoute
  '/erp/customers/$id': typeof ErpCustomersIdRoute
  '/erp/employees/$id': typeof ErpEmployeesIdRoute
  '/erp/loans/$id': typeof ErpLoansIdRoute
  '/erp/routes/$id': typeof ErpRoutesIdRoute
  '/field/collections/new': typeof FieldCollectionsNewRoute
  '/field/customers/$id': typeof FieldCustomersIdRoute
  '/app/collections/': typeof AppCollectionsIndexRoute
  '/erp/areas/': typeof ErpAreasIndexRoute
  '/erp/collections/': typeof ErpCollectionsIndexRoute
  '/erp/customers/': typeof ErpCustomersIndexRoute
  '/erp/employees/': typeof ErpEmployeesIndexRoute
  '/erp/loans/': typeof ErpLoansIndexRoute
  '/erp/routes/': typeof ErpRoutesIndexRoute
  '/field/collections/': typeof FieldCollectionsIndexRoute
  '/field/customers/': typeof FieldCustomersIndexRoute
  '/app/collections/$id/edit': typeof AppCollectionsIdEditRoute
  '/app/collections/$id/': typeof AppCollectionsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/addons'
    | '/admin'
    | '/app'
    | '/contact'
    | '/erp'
    | '/faq'
    | '/features'
    | '/field'
    | '/forgot-password'
    | '/guest-workspace'
    | '/login'
    | '/platform-policies'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/verify-otp'
    | '/admin/audit-logs'
    | '/admin/configuration'
    | '/admin/coupons'
    | '/admin/guest-plan'
    | '/admin/invoices'
    | '/admin/lenders'
    | '/admin/master-data'
    | '/admin/notifications'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/system-health'
    | '/admin/upgrade-requests'
    | '/app/calculator'
    | '/app/customers'
    | '/app/expenses'
    | '/app/notifications'
    | '/app/profile'
    | '/app/reports'
    | '/app/settings'
    | '/app/upgrade'
    | '/dev/route-smoke'
    | '/erp/analytics'
    | '/erp/business'
    | '/erp/expenses'
    | '/erp/notifications'
    | '/erp/profile'
    | '/erp/reconciliation'
    | '/erp/reports'
    | '/erp/salary'
    | '/erp/settings'
    | '/erp/subscription'
    | '/field/attendance'
    | '/field/expenses'
    | '/field/handover'
    | '/field/help'
    | '/field/notifications'
    | '/field/offline'
    | '/field/performance'
    | '/field/profile'
    | '/field/settings'
    | '/field/today-route'
    | '/admin/'
    | '/app/'
    | '/erp/'
    | '/field/'
    | '/admin/lenders/$id'
    | '/app/collections/batch'
    | '/app/collections/new'
    | '/erp/areas/$id'
    | '/erp/collections/today'
    | '/erp/customers/$id'
    | '/erp/employees/$id'
    | '/erp/loans/$id'
    | '/erp/routes/$id'
    | '/field/collections/new'
    | '/field/customers/$id'
    | '/app/collections/'
    | '/erp/areas/'
    | '/erp/collections/'
    | '/erp/customers/'
    | '/erp/employees/'
    | '/erp/loans/'
    | '/erp/routes/'
    | '/field/collections/'
    | '/field/customers/'
    | '/app/collections/$id/edit'
    | '/app/collections/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/addons'
    | '/contact'
    | '/faq'
    | '/features'
    | '/forgot-password'
    | '/guest-workspace'
    | '/login'
    | '/platform-policies'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/verify-otp'
    | '/admin/audit-logs'
    | '/admin/configuration'
    | '/admin/coupons'
    | '/admin/guest-plan'
    | '/admin/invoices'
    | '/admin/lenders'
    | '/admin/master-data'
    | '/admin/notifications'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/system-health'
    | '/admin/upgrade-requests'
    | '/app/calculator'
    | '/app/customers'
    | '/app/expenses'
    | '/app/notifications'
    | '/app/profile'
    | '/app/reports'
    | '/app/settings'
    | '/app/upgrade'
    | '/dev/route-smoke'
    | '/erp/analytics'
    | '/erp/business'
    | '/erp/expenses'
    | '/erp/notifications'
    | '/erp/profile'
    | '/erp/reconciliation'
    | '/erp/reports'
    | '/erp/salary'
    | '/erp/settings'
    | '/erp/subscription'
    | '/field/attendance'
    | '/field/expenses'
    | '/field/handover'
    | '/field/help'
    | '/field/notifications'
    | '/field/offline'
    | '/field/performance'
    | '/field/profile'
    | '/field/settings'
    | '/field/today-route'
    | '/admin'
    | '/app'
    | '/erp'
    | '/field'
    | '/admin/lenders/$id'
    | '/app/collections/batch'
    | '/app/collections/new'
    | '/erp/areas/$id'
    | '/erp/collections/today'
    | '/erp/customers/$id'
    | '/erp/employees/$id'
    | '/erp/loans/$id'
    | '/erp/routes/$id'
    | '/field/collections/new'
    | '/field/customers/$id'
    | '/app/collections'
    | '/erp/areas'
    | '/erp/collections'
    | '/erp/customers'
    | '/erp/employees'
    | '/erp/loans'
    | '/erp/routes'
    | '/field/collections'
    | '/field/customers'
    | '/app/collections/$id/edit'
    | '/app/collections/$id'
  id:
    | '__root__'
    | '/'
    | '/addons'
    | '/admin'
    | '/app'
    | '/contact'
    | '/erp'
    | '/faq'
    | '/features'
    | '/field'
    | '/forgot-password'
    | '/guest-workspace'
    | '/login'
    | '/platform-policies'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/verify-otp'
    | '/admin/audit-logs'
    | '/admin/configuration'
    | '/admin/coupons'
    | '/admin/guest-plan'
    | '/admin/invoices'
    | '/admin/lenders'
    | '/admin/master-data'
    | '/admin/notifications'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/system-health'
    | '/admin/upgrade-requests'
    | '/app/calculator'
    | '/app/customers'
    | '/app/expenses'
    | '/app/notifications'
    | '/app/profile'
    | '/app/reports'
    | '/app/settings'
    | '/app/upgrade'
    | '/dev/route-smoke'
    | '/erp/analytics'
    | '/erp/business'
    | '/erp/expenses'
    | '/erp/notifications'
    | '/erp/profile'
    | '/erp/reconciliation'
    | '/erp/reports'
    | '/erp/salary'
    | '/erp/settings'
    | '/erp/subscription'
    | '/field/attendance'
    | '/field/expenses'
    | '/field/handover'
    | '/field/help'
    | '/field/notifications'
    | '/field/offline'
    | '/field/performance'
    | '/field/profile'
    | '/field/settings'
    | '/field/today-route'
    | '/admin/'
    | '/app/'
    | '/erp/'
    | '/field/'
    | '/admin/lenders/$id'
    | '/app/collections/batch'
    | '/app/collections/new'
    | '/erp/areas/$id'
    | '/erp/collections/today'
    | '/erp/customers/$id'
    | '/erp/employees/$id'
    | '/erp/loans/$id'
    | '/erp/routes/$id'
    | '/field/collections/new'
    | '/field/customers/$id'
    | '/app/collections/'
    | '/erp/areas/'
    | '/erp/collections/'
    | '/erp/customers/'
    | '/erp/employees/'
    | '/erp/loans/'
    | '/erp/routes/'
    | '/field/collections/'
    | '/field/customers/'
    | '/app/collections/$id/edit'
    | '/app/collections/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddonsRoute: typeof AddonsRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ContactRoute: typeof ContactRoute
  ErpRoute: typeof ErpRouteWithChildren
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  FieldRoute: typeof FieldRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GuestWorkspaceRoute: typeof GuestWorkspaceRoute
  LoginRoute: typeof LoginRoute
  PlatformPoliciesRoute: typeof PlatformPoliciesRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  DevRouteSmokeRoute: typeof DevRouteSmokeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform-policies': {
      id: '/platform-policies'
      path: '/platform-policies'
      fullPath: '/platform-policies'
      preLoaderRoute: typeof PlatformPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest-workspace': {
      id: '/guest-workspace'
      path: '/guest-workspace'
      fullPath: '/guest-workspace'
      preLoaderRoute: typeof GuestWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field': {
      id: '/field'
      path: '/field'
      fullPath: '/field'
      preLoaderRoute: typeof FieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erp': {
      id: '/erp'
      path: '/erp'
      fullPath: '/erp'
      preLoaderRoute: typeof ErpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addons': {
      id: '/addons'
      path: '/addons'
      fullPath: '/addons'
      preLoaderRoute: typeof AddonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field/': {
      id: '/field/'
      path: '/'
      fullPath: '/field/'
      preLoaderRoute: typeof FieldIndexRouteImport
      parentRoute: typeof FieldRoute
    }
    '/erp/': {
      id: '/erp/'
      path: '/'
      fullPath: '/erp/'
      preLoaderRoute: typeof ErpIndexRouteImport
      parentRoute: typeof ErpRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/field/today-route': {
      id: '/field/today-route'
      path: '/today-route'
      fullPath: '/field/today-route'
      preLoaderRoute: typeof FieldTodayRouteRouteImport
      parentRoute: typeof FieldRoute
    }
    '/field/settings': {
      id: '/field/settings'
      path: '/settings'
      fullPath: '/field/settings'
      preLoaderRoute: typeof FieldSettingsRouteImport
      parentRoute: typeof FieldRoute
    }
    '/field/profile': {
      id: '/field/profile'
      path: '/profile'
      fullPath: '/field/profile'
      preLoaderRoute: typeof FieldProfileRouteImport
      parentRoute: typeof FieldRoute
    }
    '/field/performance': {
      id: '/field/performance'
      path: '/performance'
      fullPath: '/field/performance'
      preLoaderRoute: typeof FieldPerformanceRouteImport
      parentRoute: typeof FieldRoute
    }
    '/field/offline': {
      id: '/field/offline'
      path: '/offline'
      fullPath: '/field/offline'
      preLoaderRoute: typeof FieldOfflineRouteImport
      parentRoute: typeof FieldRoute
    }
    '/field/notifications': {
      id: '/field/notifications'
      path: '/notifications'
      fullPath: '/field/notifications'
      preLoaderRoute: typeof FieldNotificationsRouteImport
      parentRoute: typeof FieldRoute
    }
    '/field/help': {
      id: '/field/help'
      path: '/help'
      fullPath: '/field/help'
      preLoaderRoute: typeof FieldHelpRouteImport
      parentRoute: typeof FieldRoute
    }
    '/field/handover': {
      id: '/field/handover'
      path: '/handover'
      fullPath: '/field/handover'
      preLoaderRoute: typeof FieldHandoverRouteImport
      parentRoute: typeof FieldRoute
    }
    '/field/expenses': {
      id: '/field/expenses'
      path: '/expenses'
      fullPath: '/field/expenses'
      preLoaderRoute: typeof FieldExpensesRouteImport
      parentRoute: typeof FieldRoute
    }
    '/field/attendance': {
      id: '/field/attendance'
      path: '/attendance'
      fullPath: '/field/attendance'
      preLoaderRoute: typeof FieldAttendanceRouteImport
      parentRoute: typeof FieldRoute
    }
    '/erp/subscription': {
      id: '/erp/subscription'
      path: '/subscription'
      fullPath: '/erp/subscription'
      preLoaderRoute: typeof ErpSubscriptionRouteImport
      parentRoute: typeof ErpRoute
    }
    '/erp/settings': {
      id: '/erp/settings'
      path: '/settings'
      fullPath: '/erp/settings'
      preLoaderRoute: typeof ErpSettingsRouteImport
      parentRoute: typeof ErpRoute
    }
    '/erp/salary': {
      id: '/erp/salary'
      path: '/salary'
      fullPath: '/erp/salary'
      preLoaderRoute: typeof ErpSalaryRouteImport
      parentRoute: typeof ErpRoute
    }
    '/erp/reports': {
      id: '/erp/reports'
      path: '/reports'
      fullPath: '/erp/reports'
      preLoaderRoute: typeof ErpReportsRouteImport
      parentRoute: typeof ErpRoute
    }
    '/erp/reconciliation': {
      id: '/erp/reconciliation'
      path: '/reconciliation'
      fullPath: '/erp/reconciliation'
      preLoaderRoute: typeof ErpReconciliationRouteImport
      parentRoute: typeof ErpRoute
    }
    '/erp/profile': {
      id: '/erp/profile'
      path: '/profile'
      fullPath: '/erp/profile'
      preLoaderRoute: typeof ErpProfileRouteImport
      parentRoute: typeof ErpRoute
    }
    '/erp/notifications': {
      id: '/erp/notifications'
      path: '/notifications'
      fullPath: '/erp/notifications'
      preLoaderRoute: typeof ErpNotificationsRouteImport
      parentRoute: typeof ErpRoute
    }
    '/erp/expenses': {
      id: '/erp/expenses'
      path: '/expenses'
      fullPath: '/erp/expenses'
      preLoaderRoute: typeof ErpExpensesRouteImport
      parentRoute: typeof ErpRoute
    }
    '/erp/business': {
      id: '/erp/business'
      path: '/business'
      fullPath: '/erp/business'
      preLoaderRoute: typeof ErpBusinessRouteImport
      parentRoute: typeof ErpRoute
    }
    '/erp/analytics': {
      id: '/erp/analytics'
      path: '/analytics'
      fullPath: '/erp/analytics'
      preLoaderRoute: typeof ErpAnalyticsRouteImport
      parentRoute: typeof ErpRoute
    }
    '/dev/route-smoke': {
      id: '/dev/route-smoke'
      path: '/dev/route-smoke'
      fullPath: '/dev/route-smoke'
      preLoaderRoute: typeof DevRouteSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/upgrade': {
      id: '/app/upgrade'
      path: '/upgrade'
      fullPath: '/app/upgrade'
      preLoaderRoute: typeof AppUpgradeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/expenses': {
      id: '/app/expenses'
      path: '/expenses'
      fullPath: '/app/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers': {
      id: '/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calculator': {
      id: '/app/calculator'
      path: '/calculator'
      fullPath: '/app/calculator'
      preLoaderRoute: typeof AppCalculatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/upgrade-requests': {
      id: '/admin/upgrade-requests'
      path: '/upgrade-requests'
      fullPath: '/admin/upgrade-requests'
      preLoaderRoute: typeof AdminUpgradeRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system-health': {
      id: '/admin/system-health'
      path: '/system-health'
      fullPath: '/admin/system-health'
      preLoaderRoute: typeof AdminSystemHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/master-data': {
      id: '/admin/master-data'
      path: '/master-data'
      fullPath: '/admin/master-data'
      preLoaderRoute: typeof AdminMasterDataRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lenders': {
      id: '/admin/lenders'
      path: '/lenders'
      fullPath: '/admin/lenders'
      preLoaderRoute: typeof AdminLendersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/guest-plan': {
      id: '/admin/guest-plan'
      path: '/guest-plan'
      fullPath: '/admin/guest-plan'
      preLoaderRoute: typeof AdminGuestPlanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuration': {
      id: '/admin/configuration'
      path: '/configuration'
      fullPath: '/admin/configuration'
      preLoaderRoute: typeof AdminConfigurationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/field/customers/': {
      id: '/field/customers/'
      path: '/customers'
      fullPath: '/field/customers/'
      preLoaderRoute: typeof FieldCustomersIndexRouteImport
      parentRoute: typeof FieldRoute
    }
    '/field/collections/': {
      id: '/field/collections/'
      path: '/collections'
      fullPath: '/field/collections/'
      preLoaderRoute: typeof FieldCollectionsIndexRouteImport
      parentRoute: typeof FieldRoute
    }
    '/erp/routes/': {
      id: '/erp/routes/'
      path: '/routes'
      fullPath: '/erp/routes/'
      preLoaderRoute: typeof ErpRoutesIndexRouteImport
      parentRoute: typeof ErpRoute
    }
    '/erp/loans/': {
      id: '/erp/loans/'
      path: '/loans'
      fullPath: '/erp/loans/'
      preLoaderRoute: typeof ErpLoansIndexRouteImport
      parentRoute: typeof ErpRoute
    }
    '/erp/employees/': {
      id: '/erp/employees/'
      path: '/employees'
      fullPath: '/erp/employees/'
      preLoaderRoute: typeof ErpEmployeesIndexRouteImport
      parentRoute: typeof ErpRoute
    }
    '/erp/customers/': {
      id: '/erp/customers/'
      path: '/customers'
      fullPath: '/erp/customers/'
      preLoaderRoute: typeof ErpCustomersIndexRouteImport
      parentRoute: typeof ErpRoute
    }
    '/erp/collections/': {
      id: '/erp/collections/'
      path: '/collections'
      fullPath: '/erp/collections/'
      preLoaderRoute: typeof ErpCollectionsIndexRouteImport
      parentRoute: typeof ErpRoute
    }
    '/erp/areas/': {
      id: '/erp/areas/'
      path: '/areas'
      fullPath: '/erp/areas/'
      preLoaderRoute: typeof ErpAreasIndexRouteImport
      parentRoute: typeof ErpRoute
    }
    '/app/collections/': {
      id: '/app/collections/'
      path: '/collections'
      fullPath: '/app/collections/'
      preLoaderRoute: typeof AppCollectionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/field/customers/$id': {
      id: '/field/customers/$id'
      path: '/customers/$id'
      fullPath: '/field/customers/$id'
      preLoaderRoute: typeof FieldCustomersIdRouteImport
      parentRoute: typeof FieldRoute
    }
    '/field/collections/new': {
      id: '/field/collections/new'
      path: '/collections/new'
      fullPath: '/field/collections/new'
      preLoaderRoute: typeof FieldCollectionsNewRouteImport
      parentRoute: typeof FieldRoute
    }
    '/erp/routes/$id': {
      id: '/erp/routes/$id'
      path: '/routes/$id'
      fullPath: '/erp/routes/$id'
      preLoaderRoute: typeof ErpRoutesIdRouteImport
      parentRoute: typeof ErpRoute
    }
    '/erp/loans/$id': {
      id: '/erp/loans/$id'
      path: '/loans/$id'
      fullPath: '/erp/loans/$id'
      preLoaderRoute: typeof ErpLoansIdRouteImport
      parentRoute: typeof ErpRoute
    }
    '/erp/employees/$id': {
      id: '/erp/employees/$id'
      path: '/employees/$id'
      fullPath: '/erp/employees/$id'
      preLoaderRoute: typeof ErpEmployeesIdRouteImport
      parentRoute: typeof ErpRoute
    }
    '/erp/customers/$id': {
      id: '/erp/customers/$id'
      path: '/customers/$id'
      fullPath: '/erp/customers/$id'
      preLoaderRoute: typeof ErpCustomersIdRouteImport
      parentRoute: typeof ErpRoute
    }
    '/erp/collections/today': {
      id: '/erp/collections/today'
      path: '/collections/today'
      fullPath: '/erp/collections/today'
      preLoaderRoute: typeof ErpCollectionsTodayRouteImport
      parentRoute: typeof ErpRoute
    }
    '/erp/areas/$id': {
      id: '/erp/areas/$id'
      path: '/areas/$id'
      fullPath: '/erp/areas/$id'
      preLoaderRoute: typeof ErpAreasIdRouteImport
      parentRoute: typeof ErpRoute
    }
    '/app/collections/new': {
      id: '/app/collections/new'
      path: '/collections/new'
      fullPath: '/app/collections/new'
      preLoaderRoute: typeof AppCollectionsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/collections/batch': {
      id: '/app/collections/batch'
      path: '/collections/batch'
      fullPath: '/app/collections/batch'
      preLoaderRoute: typeof AppCollectionsBatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/lenders/$id': {
      id: '/admin/lenders/$id'
      path: '/$id'
      fullPath: '/admin/lenders/$id'
      preLoaderRoute: typeof AdminLendersIdRouteImport
      parentRoute: typeof AdminLendersRoute
    }
    '/app/collections/$id/': {
      id: '/app/collections/$id/'
      path: '/collections/$id'
      fullPath: '/app/collections/$id/'
      preLoaderRoute: typeof AppCollectionsIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/collections/$id/edit': {
      id: '/app/collections/$id/edit'
      path: '/collections/$id/edit'
      fullPath: '/app/collections/$id/edit'
      preLoaderRoute: typeof AppCollectionsIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AdminLendersRouteChildren {
  AdminLendersIdRoute: typeof AdminLendersIdRoute
}

const AdminLendersRouteChildren: AdminLendersRouteChildren = {
  AdminLendersIdRoute: AdminLendersIdRoute,
}

const AdminLendersRouteWithChildren = AdminLendersRoute._addFileChildren(
  AdminLendersRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminConfigurationRoute: typeof AdminConfigurationRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminGuestPlanRoute: typeof AdminGuestPlanRoute
  AdminInvoicesRoute: typeof AdminInvoicesRoute
  AdminLendersRoute: typeof AdminLendersRouteWithChildren
  AdminMasterDataRoute: typeof AdminMasterDataRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminSystemHealthRoute: typeof AdminSystemHealthRoute
  AdminUpgradeRequestsRoute: typeof AdminUpgradeRequestsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminConfigurationRoute: AdminConfigurationRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminGuestPlanRoute: AdminGuestPlanRoute,
  AdminInvoicesRoute: AdminInvoicesRoute,
  AdminLendersRoute: AdminLendersRouteWithChildren,
  AdminMasterDataRoute: AdminMasterDataRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminSystemHealthRoute: AdminSystemHealthRoute,
  AdminUpgradeRequestsRoute: AdminUpgradeRequestsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppCalculatorRoute: typeof AppCalculatorRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUpgradeRoute: typeof AppUpgradeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCollectionsBatchRoute: typeof AppCollectionsBatchRoute
  AppCollectionsNewRoute: typeof AppCollectionsNewRoute
  AppCollectionsIndexRoute: typeof AppCollectionsIndexRoute
  AppCollectionsIdEditRoute: typeof AppCollectionsIdEditRoute
  AppCollectionsIdIndexRoute: typeof AppCollectionsIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalculatorRoute: AppCalculatorRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUpgradeRoute: AppUpgradeRoute,
  AppIndexRoute: AppIndexRoute,
  AppCollectionsBatchRoute: AppCollectionsBatchRoute,
  AppCollectionsNewRoute: AppCollectionsNewRoute,
  AppCollectionsIndexRoute: AppCollectionsIndexRoute,
  AppCollectionsIdEditRoute: AppCollectionsIdEditRoute,
  AppCollectionsIdIndexRoute: AppCollectionsIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ErpRouteChildren {
  ErpAnalyticsRoute: typeof ErpAnalyticsRoute
  ErpBusinessRoute: typeof ErpBusinessRoute
  ErpExpensesRoute: typeof ErpExpensesRoute
  ErpNotificationsRoute: typeof ErpNotificationsRoute
  ErpProfileRoute: typeof ErpProfileRoute
  ErpReconciliationRoute: typeof ErpReconciliationRoute
  ErpReportsRoute: typeof ErpReportsRoute
  ErpSalaryRoute: typeof ErpSalaryRoute
  ErpSettingsRoute: typeof ErpSettingsRoute
  ErpSubscriptionRoute: typeof ErpSubscriptionRoute
  ErpIndexRoute: typeof ErpIndexRoute
  ErpAreasIdRoute: typeof ErpAreasIdRoute
  ErpCollectionsTodayRoute: typeof ErpCollectionsTodayRoute
  ErpCustomersIdRoute: typeof ErpCustomersIdRoute
  ErpEmployeesIdRoute: typeof ErpEmployeesIdRoute
  ErpLoansIdRoute: typeof ErpLoansIdRoute
  ErpRoutesIdRoute: typeof ErpRoutesIdRoute
  ErpAreasIndexRoute: typeof ErpAreasIndexRoute
  ErpCollectionsIndexRoute: typeof ErpCollectionsIndexRoute
  ErpCustomersIndexRoute: typeof ErpCustomersIndexRoute
  ErpEmployeesIndexRoute: typeof ErpEmployeesIndexRoute
  ErpLoansIndexRoute: typeof ErpLoansIndexRoute
  ErpRoutesIndexRoute: typeof ErpRoutesIndexRoute
}

const ErpRouteChildren: ErpRouteChildren = {
  ErpAnalyticsRoute: ErpAnalyticsRoute,
  ErpBusinessRoute: ErpBusinessRoute,
  ErpExpensesRoute: ErpExpensesRoute,
  ErpNotificationsRoute: ErpNotificationsRoute,
  ErpProfileRoute: ErpProfileRoute,
  ErpReconciliationRoute: ErpReconciliationRoute,
  ErpReportsRoute: ErpReportsRoute,
  ErpSalaryRoute: ErpSalaryRoute,
  ErpSettingsRoute: ErpSettingsRoute,
  ErpSubscriptionRoute: ErpSubscriptionRoute,
  ErpIndexRoute: ErpIndexRoute,
  ErpAreasIdRoute: ErpAreasIdRoute,
  ErpCollectionsTodayRoute: ErpCollectionsTodayRoute,
  ErpCustomersIdRoute: ErpCustomersIdRoute,
  ErpEmployeesIdRoute: ErpEmployeesIdRoute,
  ErpLoansIdRoute: ErpLoansIdRoute,
  ErpRoutesIdRoute: ErpRoutesIdRoute,
  ErpAreasIndexRoute: ErpAreasIndexRoute,
  ErpCollectionsIndexRoute: ErpCollectionsIndexRoute,
  ErpCustomersIndexRoute: ErpCustomersIndexRoute,
  ErpEmployeesIndexRoute: ErpEmployeesIndexRoute,
  ErpLoansIndexRoute: ErpLoansIndexRoute,
  ErpRoutesIndexRoute: ErpRoutesIndexRoute,
}

const ErpRouteWithChildren = ErpRoute._addFileChildren(ErpRouteChildren)

interface FieldRouteChildren {
  FieldAttendanceRoute: typeof FieldAttendanceRoute
  FieldExpensesRoute: typeof FieldExpensesRoute
  FieldHandoverRoute: typeof FieldHandoverRoute
  FieldHelpRoute: typeof FieldHelpRoute
  FieldNotificationsRoute: typeof FieldNotificationsRoute
  FieldOfflineRoute: typeof FieldOfflineRoute
  FieldPerformanceRoute: typeof FieldPerformanceRoute
  FieldProfileRoute: typeof FieldProfileRoute
  FieldSettingsRoute: typeof FieldSettingsRoute
  FieldTodayRouteRoute: typeof FieldTodayRouteRoute
  FieldIndexRoute: typeof FieldIndexRoute
  FieldCollectionsNewRoute: typeof FieldCollectionsNewRoute
  FieldCustomersIdRoute: typeof FieldCustomersIdRoute
  FieldCollectionsIndexRoute: typeof FieldCollectionsIndexRoute
  FieldCustomersIndexRoute: typeof FieldCustomersIndexRoute
}

const FieldRouteChildren: FieldRouteChildren = {
  FieldAttendanceRoute: FieldAttendanceRoute,
  FieldExpensesRoute: FieldExpensesRoute,
  FieldHandoverRoute: FieldHandoverRoute,
  FieldHelpRoute: FieldHelpRoute,
  FieldNotificationsRoute: FieldNotificationsRoute,
  FieldOfflineRoute: FieldOfflineRoute,
  FieldPerformanceRoute: FieldPerformanceRoute,
  FieldProfileRoute: FieldProfileRoute,
  FieldSettingsRoute: FieldSettingsRoute,
  FieldTodayRouteRoute: FieldTodayRouteRoute,
  FieldIndexRoute: FieldIndexRoute,
  FieldCollectionsNewRoute: FieldCollectionsNewRoute,
  FieldCustomersIdRoute: FieldCustomersIdRoute,
  FieldCollectionsIndexRoute: FieldCollectionsIndexRoute,
  FieldCustomersIndexRoute: FieldCustomersIndexRoute,
}

const FieldRouteWithChildren = FieldRoute._addFileChildren(FieldRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddonsRoute: AddonsRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ContactRoute: ContactRoute,
  ErpRoute: ErpRouteWithChildren,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  FieldRoute: FieldRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GuestWorkspaceRoute: GuestWorkspaceRoute,
  LoginRoute: LoginRoute,
  PlatformPoliciesRoute: PlatformPoliciesRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  DevRouteSmokeRoute: DevRouteSmokeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
